[general]
log_level = 5
#log_path = "/var/log/golang"
name = "camera-gateway-bridge"
addr = "192.168.1.64:80"
username = "admin"
password = "ADMIN123"
snapshot_path = "D://workspace/go/src/snapshot"


[camera]
mqtt_server="tcp://127.0.0.1:1883"
mqtt_username="root"
mqtt_password="0b32b351-9c3b-44e4-892d-8ab89ce3775c"

[file_server]
url="https://127.0.0.1:9096/v1.0/file"